logserver:
  image: mongo:3.2.8

minelev_services_base:
  image: telemark/tfk-seneca-base
  container_name: minelev_services_base
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_buddy:
  image: telemark/tfk-seneca-mesh-buddy
  container_name: minelev_services_buddy
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_mail:
  image: telemark/tfk-seneca-mesh-mail-sendgrid
  container_name: minelev_services_mail
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_varsle_kontaktlarer:
  image: telemark/tfk-seneca-mesh-minelev-varsle-kontaktlarer
  container_name: minelev_services_varsle_kontaktlarer
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_counter:
  image: telemark/tfk-seneca-counter
  container_name: minelev_services_counter
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_stats_dispatcher:
  image: telemark/tfk-seneca-mesh-minelev-stats-dispatcher
  container_name: minelev_stats_dispatcher
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_queue:
  image: telemark/tfk-seneca-queue
  container_name: minelev_services_queue
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_webserver:
  image: telemark/minelev
  env_file: minelev.env
  ports:
    - "80:80"
  links:
   - logserver