logserver:
  image: mongo:3.2.6

queueserver:
  image: mongo:3.2.6

minelev_services_base:
  image: telemark/tfk-seneca-base
  container_name: minelev_services_base
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_mail:
  image: telemark/tfk-seneca-mesh-mail-sendgrid
  container_name: minelev_services_mail
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_counter:
  image: telemark/tfk-seneca-counter
  container_name: minelev_services_counter
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_services_queue:
  image: telemark/tfk-seneca-queue
  container_name: minelev_services_queue
  env_file: minelev.env
  restart: always
  net: container:minelev_webserver

minelev_webserver:
  image: telemark/minelev
  env_file: minelev.env
  ports:
    - "80:80"
  links:
   - logserver
   - queueserver